---
title: "ggplot Piper Diagram"
author: "Marko Lipka"
date: "January 24, 2018"
output: github_document
---

# Example

```{r setup}
source("ggplot_piper.R")
```

```{r data}
data <- as.data.frame(list("Ca"  = c(43, 10, 73, 26, 32),
                        "Mg"  = c(30, 50, 3, 14, 12),
                        "Cl"  = c(24, 10, 12, 30, 43),
                        "SO4" = c(24, 10, 12, 30, 43),
                        "WaterType" = c(2, 2, 1, 2, 3)),
                   row.names = c("A", "B", "C", "D", "E"))
data
```

```{r transformed}
piper_data <- transform_piper_data(Ca = data$Ca,
                                   Mg = data$Mg,
                                   Cl = data$Cl,
                                   SO4 = data$SO4,
                                   name = data$WaterType)

piper_data
```

```{r, fig.width=10, fig.asp=1}
ggplot_piper() + 
  geom_point(aes(x, y,
                 colour = factor(observation),
                 shape  = factor(observation)), 
             size=4, data = piper_data) + 
  scale_colour_manual(name="legend name", values=c("#999999", "#E69F00", "#56B4E9"), labels=c("Control", "Treatment 1", "Treatment 2")) +
  scale_shape_manual(name="legend name", values=c(1,2,3), labels=c("Control", "Treatment 1", "Treatment 2")) +
  theme(legend.position = c(.9, .9))
```




